-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.students
(
    student_id SERIAL PRIMARY KEY,
    name character varying(50) NOT NULL,
    surname character varying(50) NOT NULL,
    birth_date date NOT NULL,
    phone character varying(11),
    primary_skill character varying(50),
    created_date date NOT NULL,
    updated_date date,
    PRIMARY KEY (student_id)
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    subject_id SERIAL PRIMARY KEY,
    name character varying(50) NOT NULL,
    tutor character varying(50) NOT NULL,
    created_date date NOT NULL,
    updated_date date,
    PRIMARY KEY (subject_id)
);

CREATE TABLE IF NOT EXISTS public.results
(
    result_id SERIAL PRIMARY KEY,
    student bigint NOT NULL,
    subject bigint NOT NULL,
    created_date date NOT NULL,
    grade bigint,
    status boolean,
    PRIMARY KEY (result_id)
);

ALTER TABLE IF EXISTS public.results
    ADD CONSTRAINT student_id FOREIGN KEY (student)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.results
    ADD CONSTRAINT subject_id FOREIGN KEY (subject)
    REFERENCES public.subjects (subject_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;